// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogpageFields {
  page: any;

  /** Ссылка */
  slug: string;

  /** Обложка публикации */
  cover: Asset;

  /** Автор публикации */
  author: string;

  /** Дата публикации (прим. 22 Июня) */
  date: string;

  /** Теги */
  tags?: string | undefined;

  /** Заголовок */
  title: string;

  /** Подзаголовок */
  description: string;

  /** Статья */
  content: Document;

  /** Блок связи с менеджером */
  whatsapp: boolean;
}

/** Выпуск блога */

export interface IBlogpage extends Entry<IBlogpageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogpage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICategoryFields {
  /** Название раздела */
  name: string;

  /** Ссылка */
  slug: string;

  /** Стандартная переадресация  */
  redirect: string;
}

/** Верхний уровень сайта */

export interface ICategory extends Entry<ICategoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "category";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IOfferFields {
  page: any;

  /** Ссылка */
  slug: string;

  /** Превью услуги */
  cover: Asset;

  /** Тип услуги */
  subtype: string;

  /** Название услуги */
  title: string;

  /** Описание услуги */
  description: string;

  /** Статья про услугу */
  content: Document;

  /** Блок связи с менеджером */
  whatsapp?: boolean | undefined;
}

/** Услуга предприятия */

export interface IOffer extends Entry<IOfferFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "offer";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IOffersFields {
  /** Категория услуги */
  offercat: string;

  /** Название категории услуги */
  name: string;

  /** Описание категории услуги */
  description: string;
}

export interface IOffers extends Entry<IOffersFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "offers";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISubpageFields {
  page: any;
  
  /** Категория страницы */
  cattype: string;

  /** Ссылка */
  slug: string;

  /** Отображение в навигации */
  showInRouter?: boolean | undefined;

  /** Заголовок */
  title: string;

  /** Подзаголовок */
  description?: string | undefined;

  /** Статья */
  content: Document;

  /** Блок связи с менеджером */
  whatsapp: boolean;
}

/** Страница сайта */

export interface ISubpage extends Entry<ISubpageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "subpage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "blogpage"
  | "category"
  | "offer"
  | "offers"
  | "subpage";

export type IEntry = IBlogpage | ICategory | IOffer | IOffers | ISubpage;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
